#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/rocket"
require "pathname"

EXEC_PATH = "bin/rocket"
CURRENT_DIR = Dir.pwd.freeze

loop do
  if File.file?(EXEC_PATH)
    exec Gem.ruby, EXEC_PATH, *ARGV
    break
  end
  break if Pathname.new(Dir.pwd).root?

  Dir.chdir("..")
end

Dir.chdir(CURRENT_DIR)
Rocket::CLI::Default.start
